ChairOfStructuralMechanicsTUM/Mechanics_Apps

SDOF/Coord.py
SDOF/Dashpot.py
SDOF/Mass.py
SDOF/README.md
SDOF/Spring.py
SDOF/description.html
SDOF/main.py
SDOF/templates/index.html

Adding a new app for the single-degree-of-freedom system based on its analytical solution.

New SDOF app

---

Collision/Functions.py
Collision/main.py

The sliders in the collision app are now disabled, when the balls are moving. The sliders for velocity and direction are updated after "Pause" is pressed.
@axelgreim please check, if I did not see any errors

Improvements in the collision app

---

Buckling/main.py
Coriolis_force/description.html
Coriolis_force/main.py
Diffraction/description.html
Diffraction/main.py
Pendulum/description.html
Pendulum/main.py
Stopping_distances/main.py
shared/latex_div.ts

`$$` can now be used for display mode.
Updated the Latex support for all published apps.

Improve latex support

---

Stopping_distances/Graphs.py
Stopping_distances/Problem.py
Stopping_distances/TestSolutions.py
Stopping_distances/Visualisation.py
Stopping_distances/main.py

This hopefully fixes the stopping distances app

Remove wildcard imports

---

Balken_AD/main.py
Balken_AD/static/images/auflager01.svg
Balken_AD/static/images/auflager02.svg
Maxwell_Reciprocity/description.html
Maxwell_Reciprocity/description1.html
Maxwell_Reciprocity/main.py
Mohr_Circle/main.py

Thank you @SaschaKubisch for your work. This branch can be pulled into mater according to my opinion now. Please use in future for each app, which you are improving or developing an own branch. Therefore we do not get confused with different states of different apps. If you are still working on the Balken_AD app, please crate a new brach for further enhancements on this app.

Maxwells Reciprocity

---

DevelopmentGuideline.md

Merge updated Developer Guidelines into Master

Update dev guidlines

---

Collision/description.html
Collision/main.py

Sliders are now activated after reset has been pressed.

Collision updates

---

Vector_addition/main.py

Update vector addition

---

Damped_oscillator/README.md
Damped_oscillator/description.html
Damped_oscillator/main.py

latex 's' might seem a bit too small in fractions

Damped oscillator me

---

Collision/main.py

LaTeX integration for the unit m/s would be possible, but slider sizes need to be adjusted in this case. See screenshot below.

Collision me

---

Stopping_distances/SD_Constants.py
Stopping_distances/SD_Graphs.py
Stopping_distances/SD_Problem.py
Stopping_distances/SD_Problem_legacy.py
Stopping_distances/SD_Shape.py
Stopping_distances/SD_TestSolutions.py
Stopping_distances/SD_Visualisation.py

runs using the new versions but needs to be improved regarding user inputs and distance dependent velocity case

Stopping distances me

---

README.md
Vector_addition/main.py
Vector_decomposition/main.py

Vector apps me

---

Dummy/description.html
Dummy/description_animation.html
Dummy/description_encoding.html
Dummy/description_end.html
Dummy/description_hide.html
Dummy/description_loading.html
Dummy/description_style.html
Dummy/main.py
Template_App/TA_custom_class.py
Template_App/description.html
Template_App/main.py

Updates for Dummy and Template App:
- better styling
- links
- improved comments
- fixed typos

Dummy template me

---

Fourier_Transform/README.md
Fourier_Transform/description.html
Fourier_Transform/main.py
Fourier_Transform/templates/index.html

adding app for fourier transform -> further improvements will follow

Fourier transform vl

---

Shock_Response_Spectra/description.html
Shock_Response_Spectra/main.py

fixing buttons and figure labels

Shock response spectra me

---

System_of_Beams/Libs/geometriccalc.py
System_of_Beams/Libs/outputvisualization.py
System_of_Beams/Libs/symbolictoolbox.py

Update of values in visualization

System of beams mh

---

Bending_Beam/description_de.html
Bending_Beam/main.py
Bending_Beam/static/strings.json

Bending beam mh

---

2D_cantilever_beam/description_de.html
2D_cantilever_beam/main.py
2D_cantilever_beam/static/images/Circular_de.svg
2D_cantilever_beam/static/images/DoubleT_de.svg
2D_cantilever_beam/static/images/Rectangular_de.svg
2D_cantilever_beam/static/images/Triangular_de.svg
2D_cantilever_beam/static/strings.json

2 d cantilever beam mh

---

Normal_Force_Rod/description_de.html
Normal_Force_Rod/main.py
Normal_Force_Rod/static/strings.json

Normal force rod mh

---

Base_excited_oscillator/description_de.html
Base_excited_oscillator/main.py
Base_excited_oscillator/static/strings.json

Base excited oscillator mh

---

Shock_Response_Spectra/main.py

change color of arrow to orange, resize figure

---

Damped_oscillator/description_de.html
Damped_oscillator/main.py
Damped_oscillator/static/strings.json

Damped oscillator mh

---

Transversal_strain_test/caption_de.html
Transversal_strain_test/description.html
Transversal_strain_test/description_de.html
Transversal_strain_test/main.py
Transversal_strain_test/static/strings.json

Transversal strain test mh

---

Pendulum/description.html
Pendulum/description_de.html
Pendulum/main.py
Pendulum/static/strings.json

Pendulum mh
